---
addons:
  sonarcloud:
    organization:   "$SONAR_ORGANIZATION"
    token:
      secure:       "$SONAR_TOKEN"
    github_token:
      secure:       "$GITHUB_ACCESS_TOKEN"
    branches:
      - master
      - /[build|chore|ci|docs|feat|fix|perf|refactor|revert|spike|style|test].*/
jdk:
  - oraclejdk8
language:           node_js
cache:
  directories:
    - '$HOME/.sonar/cache'
notifications:
  email:            false
node_js:
  - 8
  - 7
  - 6
  - node
before_script:
  - npm prune
script:
  - npm test
  - sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN -X
after_script:
  - cat ./coverage/lcov.info | coveralls
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
